In [1]:
import numpy as np


In [2]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np. full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [4]:
a10to50 = np.arange(10, 51, 1)

In [7]:
print(a10to50)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [10]:
np.arange(0,9,1).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.random.normal(0, 0.5, (5,5))

array([[ 0.24432697,  0.82875494,  1.01874513, -0.77258672,  0.31523091],
       [ 0.23770907, -0.08583112,  0.52993391, -0.3962459 , -0.64138145],
       [ 1.09336966, -0.81843451,  0.89117307,  0.41858488, -0.33716193],
       [-0.91170665,  0.19409845,  0.37084098, -0.50927824, -0.17740625],
       [-0.13748387,  0.42581137, -0.52224112,  0.49737394,  0.30292866]])

In [13]:
np.linspace(0.01, 1.0, 100).reshape(10, 10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [14]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [15]:
a125 = np.random.randint(2, 25, 25).reshape(5, 5)

In [17]:
print (a125)


[[20 17 17 22  2]
 [ 8 22 24 13 22]
 [ 2  4 21 18 10]
 [19 20 21  4 23]
 [ 2 19 14  9  9]]


In [18]:
a125.sum()

362

In [19]:
a125.mean()

14.48

In [20]:
np.std(a125)

7.365432777508733

In [21]:
a125.sum(axis=0)

array([51, 82, 97, 66, 66])

In [22]:
a55 = np.random.randint(1, 100, (5, 5))

In [23]:
print (a55)

[[97 52 59 33 99]
 [65 25 43  3 14]
 [63 24  7 62 88]
 [40 19 62 79 22]
 [10 34 32 66 50]]


In [24]:
np.median(a55)

43.0

In [25]:
a55.min()

3

In [26]:
a55.max()

99

In [27]:
x = np.random.randint(1, 100, (4, 3))

In [29]:
print (x.T)

[[82 74 39 56]
 [48 29 10 92]
 [89 91 20 85]]


In [30]:
mx = np.random.random((4, 4))

In [31]:
my = np.random.random((4, 3))

In [32]:
print (mx)

[[0.51783329 0.92516373 0.44548461 0.34588931]
 [0.0550091  0.80233686 0.28756662 0.0257539 ]
 [0.29579832 0.29857529 0.37020458 0.57307746]
 [0.49476707 0.29131412 0.80879222 0.28959848]]


In [33]:
print (my)

[[0.39438642 0.56676204 0.75473939]
 [0.44727461 0.06772875 0.18474168]
 [0.58139779 0.34085904 0.90441777]
 [0.88175158 0.20205212 0.6547416 ]]


In [34]:
my = np.append(my, np.zeros((4, 1)), axis=1)

In [35]:
print (my)

[[0.39438642 0.56676204 0.75473939 0.        ]
 [0.44727461 0.06772875 0.18474168 0.        ]
 [0.58139779 0.34085904 0.90441777 0.        ]
 [0.88175158 0.20205212 0.6547416  0.        ]]


In [36]:
print (mx + my)

[[0.91221971 1.49192577 1.200224   0.34588931]
 [0.50228371 0.8700656  0.47230829 0.0257539 ]
 [0.87719611 0.63943434 1.27462234 0.57307746]
 [1.37651865 0.49336624 1.46353383 0.28959848]]


In [37]:
mxd = np.random.random((3, 4))
myd = np.random.random((4, 3))

In [39]:
print (np.matmul(mxd, myd))

[[1.28136997 1.20982818 1.02831432]
 [1.15413527 1.2236436  0.87272159]
 [1.66213425 1.42134106 0.98412685]]


In [40]:
print (np.multiply(mxd.T, myd))

[[0.25442117 0.19771984 0.14110714]
 [0.51640344 0.03260733 0.04893496]
 [0.35532592 0.48926014 0.53030356]
 [0.15521944 0.50405628 0.26378119]]
